### ISSUE TITLE
"pre" and "post" values are incorrect

### ISSUE THREAD

**Issue by jlhawn** [vbatts/tar-split#3]
Take this [excerpt from `main.go`](https://github.com/vbatts/tar-split/blob/686addad772e112c459f7101d1b9f0a82fb7dc2f/main.go#L57-71):

```go
				pre := tr.RawBytes()
				output.Write(pre)
				sum += int64(len(pre))

				var i int64
				if i, err = io.Copy(output, tr); err != nil {
					log.Println(err)
					break
				}
				sum += i

				// I've never seen this be populated
				post := tr.RawBytes()
				output.Write(post)
				sum += int64(len(post))
```

The `// I've never seen this be populated` comment can be explained because the first call:

```go
pre := tr.RawBytes()
```

returns all of the raw bytes and then [resets the rawbytes buffer](https://github.com/vbatts/tar-split/blob/686addad772e112c459f7101d1b9f0a82fb7dc2f/archive/tar/reader.go#L56):

```go
func (tr *Reader) RawBytes() []byte {
	if !tr.RawAccounting {
		return nil
	}
	if tr.rawBytes == nil {
		tr.rawBytes = bytes.NewBuffer(nil)
	}
	// if we've read them, then flush them.
	defer tr.rawBytes.Reset()
	return tr.rawBytes.Bytes()
}
```

ALSO

I would assume that the `pre` value is the bytes from the beginning of an entry header to the ending of any padding before the file entry contents, and that the `post` value is the padding bytes from the ending of the file entry contents to the end of the next 512 bytes block.

This is not currently the case. Take this excerpt from the example in the README:

```bash
$ ./main tar-split.tar
2015/02/20 15:00:58 writing "tar-split.tar" to "tar-split.tar.out"
pax_global_header pre: 512 read: 52 post: 0
LICENSE pre: 972 read: 1075 post: 0
README.md pre: 973 read: 1004 post: 0
..
```

The first entry, `pax_global_header` has 512 bytes of `pre` data. This is the Tar header which is always going to be a multiple of 512 bytes. The `read` portion is 52 bytes (the size of the file), but `post` is 0 bytes *but* it should be `512 - (read % 512) -> 460` bytes of padding!

Where did these 460 bytes of padding go? They went to the `pre` of the next entry! The `LICENSE` has 972 bytes of `pre` data. This is weird because it's not a multiple of 512 bytes. It's 512 bytes for the header + the 460 bytes of padding from the previous entry.

**Comment by jlhawn** [comment]
@vbatts perhaps the best course of action is to just not display a `post` value? It doesn't seem to be that useful anyway. What do you think?

**Comment by vbatts** [comment]
good explanation. I'll remove it shortly. :-)
