### ISSUE TITLE
Fix goreportcard errors

### ISSUE THREAD

**Issue by erikh** [vbatts/tar-split#39]
Happy to do this work in the next month or so.

Reference: https://goreportcard.com/report/github.com/vbatts/tar-split

I have a pretty cool script for this, icecrime/poule is using it now too:

https://github.com/box-builder/box/blob/master/checks.sh

This could be added to your test suite to ensure it doesn't go down again. It will put the report card at 100% when it passes.

Since the gocyclo & golint errors in particular will probably require some refactors, if you're willing to accept this request, we should probably discuss how the code should be reorganized first.

Hope this is useful, thanks.

**Comment by vbatts** [comment]
Oh cool. That seems​ helpful for sure
