### ISSUE TITLE
Doesn't support tar entries > 8gb

### ISSUE THREAD

**Issue by dgageot** [vbatts/tar-split#47]
tar-split is used by docker and makes it impossible to build an image that contains some layers that are >8gb.

See the issue in Docker: https://github.com/moby/moby/issues/37581
See the code to reproduce the issue out of Docker: https://gist.github.com/dgageot/0007b4cbfa08f7cf95e93ba0db3bc12a

**Comment by vbatts** [comment]
oh neat. That's a nice find. I'll have to dust off https://github.com/vbatts/tar-split/pull/35 and rebase my changes for something like go1.10.x

**Comment by kolyshkin** [comment]
> for something like go1.10.x

or go 1.11 :cat:

**Comment by vbatts** [comment]
Fair. Upstream `archive/tar` has had more changes than I was expecting. 😫

-------- Original Message --------

**Comment by kolyshkin** [comment]
It is probably easier to port `RawAccounting` changes to archive/tar from go 1.11 than the other way around.

**Comment by vbatts** [comment]
I wonder if @dsnet has an opinion on how and whether we could get the `RawAccounting` functionality upstreamed to `archive/tar`
