### ISSUE TITLE
Request for a new release tag

### ISSUE THREAD

**Issue by steveb** [vbatts/tar-split#50]
Can you please tag a release so the --compress change can be packaged? Also it looks like version/version.go is out of sync with the current release tag.

Thanks very much

**Comment by vbatts** [comment]
On 22/11/18 22:35 -0500, Steve Baker wrote:
>   Can you please tag a release so the --compress change can be packaged?
>   Also it looks like version/version.go is out of sync with the current
>   release tag.
>
>   Thanks very much

sure thing. Just pushed a v0.11.1
