### ISSUE TITLE
asm.go at /4th/tar-split/cmd/tar-split   invalid argument c.Args() (type cli.Args) for len  

### ISSUE THREAD

**Issue by asellappen** [vbatts/tar-split#51]
2.50s$ go vet ./...
# github.com/asellappen/tar-split/cmd/tar-split [github.com/asellappen/tar-split/cmd/tar-split.test]
cmd/tar-split/asm.go:15:8: invalid argument c.Args() (type cli.Args) for len
cmd/tar-split/asm.go:16:65: invalid argument c.Args() (type cli.Args) for len
cmd/tar-split/checksize.go:19:8: invalid argument c.Args() (type cli.Args) for len
cmd/tar-split/checksize.go:22:16: cannot range over c.Args() (type cli.Args)
cmd/tar-split/disasm.go:16:8: invalid argument c.Args() (type cli.Args) for len
cmd/tar-split/disasm.go:25:13: invalid operation: c.Args()[0] (type cli.Args does not support indexing)
cmd/tar-split/disasm.go:28:30: invalid operation: c.Args()[0] (type cli.Args does not support indexing)
cmd/tar-split/disasm.go:62:81: invalid operation: c.Args()[0] (type cli.Args does not support indexing)
cmd/tar-split/main.go:16:5: app.Author undefined (type *cli.App has no field or method Author

found the issue asm.go at /4th/tar-split/cmd/tar-split  

func CommandAsm(c *cli.Context) {
        if len(c.Args()) > 0 {
                logrus.Warnf("%d additional arguments passed are ignored", len(c.Args()))
        }

**Comment by vbatts** [comment]
Thanks for the report!

What version of golang are you using? and is this on HEAD 620714a4c508c880ac1bdda9c8370a2b19af1a55 of tar-split?

I just ran this with go1.15.3 and did not see the same:
```shell
vbatts@melisma:~/src/github.com/vbatts/tar-split$ go vet ./...
vbatts@melisma:~/src/github.com/vbatts/tar-split$ 
```

**Comment by vbatts** [comment]
I just jumped to go1.12.17, and now see this error.
