### ISSUE TITLE
Empty entry added when no padding at end of file

### ISSUE THREAD

**Issue by mikenorgate** [vbatts/tar-split#65]
I've run into an issue where an empty entry is added when reading a tar stream and I wanted to check if this was expected behaviour or not?

I have a scenario where this read operation https://github.com/vbatts/tar-split/blob/f966b140968ad6826e00ea8231f7443519d1c5a6/tar/asm/disassemble.go#L130 is retuning `n=0` and `err=EOF`

In other places in this code you are checking that the length of the payload is greater than 0 https://github.com/vbatts/tar-split/blob/f966b140968ad6826e00ea8231f7443519d1c5a6/tar/asm/disassemble.go#L57-L66

Should this length check also be applied when adding the padding chunk or is adding the empty entry desired?

**Comment by vbatts** [comment]
thanks for reporting. Do you have a reproducer for this situation?

**Comment by tianon** [comment]
Ooh, if this is what I think it is (the trailing "EOF" entry), then it might be useful to you that I just recently refactored the layer on `tianon/true:oci` to not include that (in case you need a very small test case).

**Comment by vbatts** [comment]
I just tried your layer from that `tianon/true:oci` image, but it passes right through this code and doesn't hit the issue.
```patch
diff --git a/tar/asm/assemble_test.go b/tar/asm/assemble_test.go
index 6cb7850..cfbcca6 100644
--- a/tar/asm/assemble_test.go
+++ b/tar/asm/assemble_test.go
@@ -140,6 +140,7 @@ var testCases = []struct {
        {"./testdata/iso-8859.tar.gz", "ddafa51cb03c74ec117ab366ee2240d13bba1ec3", 10240},
        {"./testdata/extranils.tar.gz", "e187b4b3e739deaccc257342f4940f34403dc588", 10648},
        {"./testdata/notenoughnils.tar.gz", "72f93f41efd95290baa5c174c234f5d4c22ce601", 512},
+       {"./testdata/1c51fc286aa95d9413226599576bafa38490b1e292375c90de095855b64caea6", "946caa03167a8cc707db6ff9785608b652e631dc", 1024},
 }

 func TestTarStream(t *testing.T) {
```
